# Generated by Django 4.2 on 2024-05-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.IntegerField()),
                ('homepage', models.URLField()),
                ('original_language', models.CharField(max_length=2)),
                ('original_title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('release_date', models.DateTimeField()),
                ('revenue', models.IntegerField()),
                ('runtime', models.FloatField()),
                ('status_film', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('images', models.ImageField(upload_to='photos/movies')),
                ('genres', models.ManyToManyField(to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='CastCredit',
            fields=[
                ('character_name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('gender', models.IntegerField()),
                ('order', models.IntegerField()),
                ('actor', models.ManyToManyField(to='store.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.movie')),
            ],
        ),
    ]
