# Generated by Django 4.2 on 2024-05-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0002_actor_movie_castcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(limit_choices_to={'some_condition': True}, to='category.category'),
        ),
    ]
