# Generated by Django 4.2 on 2024-05-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_genre_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcredit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
