# Generated by Django 4.2 on 2024-05-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_castcredit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcredit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
