# Generated by Django 4.2 on 2024-05-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_castcredit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='short_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not specified'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0),
        ),
        migrations.RemoveField(
            model_name='castcredit',
            name='actor',
        ),
        migrations.AlterField(
            model_name='castcredit',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not specified'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='castcredit',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.actor'),
        ),
    ]
