# Generated by Django 4.2 on 2024-05-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_actor_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='short_name',
            field=models.CharField(default='N/A1', max_length=30, null=True),
        ),
    ]
