# Generated by Django 4.2 on 2024-05-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_actor_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='short_name_2',
            field=models.CharField(blank=True, default='N/A1', max_length=30),
        ),
    ]
