# Generated by Django 4.2 on 2024-05-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_reviewrating_product_remove_variation_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default='n/a', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='n/a', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='slug',
            field=models.SlugField(default='n/a', max_length=200, unique=True),
        ),
    ]
