# Generated by Django 4.2 on 2024-05-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_product_cartitem_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
    ]
