# Generated by Django 4.2 on 2024-05-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_product_price_ordermovie_movie_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordermovie',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
